### ISSUE TITLE
Its a bug or no?

### ISSUE THREAD

**Issue by Kitsunyy** [TheCodex6824/ThaumcraftResearchPatcher#1]
I wrote everything right, but the text display is not quite normal...
![image](https://user-images.githubusercontent.com/56004431/106313328-10f52c00-6279-11eb-9f84-9e51c07141d8.png)

**Comment by Kitsunyy** [comment]
And this...
![image](https://user-images.githubusercontent.com/56004431/106315544-6da61600-627c-11eb-8c6a-495b73bac307.png)

**Comment by Kitsunyy** [comment]
I think the problem is this 
![image](https://user-images.githubusercontent.com/56004431/106317440-60d6f180-627f-11eb-8a89-b0b38b78f41b.png)

**Comment by TheCodex6824** [comment]
That's not a bug, it places the category name in a language key. Normally, addons would have something like this in their language files:
`tc.research_category.TEST=Test Category`

For research patcher purposes, I assume that people that need that are using either a custom resource pack or some other resource loader mod. I thought there was a resource loader mod out there already for 1.12, but if there isn't or it's bad I guess I can add that to my bucket list.

In the future, please do not post Thaumcraft's code as [the license states it is not open source.](https://www.curseforge.com/project/223628/license). I appreciate the attempt to help, but if there's ever a code issue that needs to be investigated I can look at the code privately.

**Comment by Kitsunyy** [comment]
Thank you very much...

**Comment by Kitsunyy** [comment]
Thank you very much...
