### ISSUE TITLE
[Bug] Aspects object not optional as it should be

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumcraftResearchPatcher#10]
I updated the mod and all the categories and research I added don't show up now.
Any idea why this is?

**Comment by VerySaltyOreos** [comment]
I should mention I tried every version, the only one that works is the original.
I also tried on a new profile with an empty category, same result.

**Comment by TheCodex6824** [comment]
Can I see your log file?

**Comment by VerySaltyOreos** [comment]
> Can I see your log file?

https://gist.github.com/VerySaltyOreos/c388c85a822275f64e720f9be153e0c3
This is from my small testing profile where I work on things that require a lot of relaunches

**Comment by VerySaltyOreos** [comment]
That's on an older version since I was seeing if swapping versions worked, I can do it on the latest version if needed

**Comment by TheCodex6824** [comment]
Try the latest version, the previous versions had an issue where some addons' categories would get incorrectly removed.

**Comment by VerySaltyOreos** [comment]
https://gist.github.com/VerySaltyOreos/0be10195b61e9d022b7383213ccae1b0
There's the log for when it's on the latest version

**Comment by TheCodex6824** [comment]
Can I see the debug.log? It seems like the coremod is being detected, but the normal mod code that handles adding research and such isn't loading.

**Comment by VerySaltyOreos** [comment]
where do I find that, I'm not familiar with most stuff

**Comment by TheCodex6824** [comment]
> where do I find that, I'm not familiar with most stuff

It should be in your logs folder in your minecraft instance, called debug.log.

**Comment by VerySaltyOreos** [comment]
Maybe it's because it's a curseforge instance, but all that's there is latest.log and a bunch of zips with the date, each containing a log

**Comment by VerySaltyOreos** [comment]
From what I can tell, the zips are just the previous latest.log files
Idk how to get ahold of what you're asking for

**Comment by TheCodex6824** [comment]
Looks like the curse launcher breaks that log so don't worry about it. I'll try to figure out what's going on, but in the meantime, if you start the game and go to mods, do you see the research patcher in the sidebar? If so, make sure it's not disabled.

**Comment by VerySaltyOreos** [comment]
It's enabled and lets me edit the config from in game, and the way curseforge disabled mods is by changing their file type.
The beta version worked fine, just the newer versions don't work.

**Comment by TheCodex6824** [comment]
It was hard to spot with things spitting out tons of errors in that log but:

> [11:30:49] [Client thread/ERROR]: categories.json: Error reading file: Key aspects is missing

I forgot that was an optional field, so in the cleanup I did that got accidentally turned into an error-raising condition. Adding in an empty `aspects` object should fix things.

**Comment by VerySaltyOreos** [comment]
> It was hard to spot with things spitting out tons of errors in that log but:
> 
> > [11:30:49] [Client thread/ERROR]: categories.json: Error reading file: Key aspects is missing
> 
> I forgot that was an optional field, so in the cleanup I did that got accidentally turned into an error-raising condition. Adding in an empty `aspects` object should fix things.

so just an empty aspects section on the json should fix it? I'll try with the example from wiki

**Comment by VerySaltyOreos** [comment]
Adding `"aspects": {},` to the categories fixed them, thanks!
Excited to try out the scanning methods added.

**Comment by TheCodex6824** [comment]
Slightly unrelated but I noticed that part of the Thaumic Augmentation coremod seemed to break in your log, so can I have your mod list? I try to stay on top of those because they are so brittle.

**Comment by VerySaltyOreos** [comment]
Exported the profile and copied the modlist HTML

Mystical Gears (by RCXcrafter)
Display (by Martacus)
MixinBooter (by Rongmario)
ThaumTweaks (by GrigLog)
ConnectedTexturesMod (by tterrag1098)
Souls (by Chaosyr)
Thaumic JEI (by Buuz135)
Thaumic Additions: Reconstructed (by Zeitheron)
CraftTweaker (by Jaredlll08)
Fish's Undead Rising (by fish0016054)
Thaumcraft Research Patcher (by TheCodex6824)
Thaumic Redundancy (by MsRandom1)
Embers Rekindled (by BordListian)
Applied Energistics 2 (by AlgorithmX2)
MTLib (by Jaredlll08)
CoFH Core (by TeamCoFH)
WorldEdit (by sk89q)
ContentTweaker (by Jaredlll08)
Baubles (by Azanor13)
Thaumic Tinkerer (by gaeakat)
Spartan Weaponry (by ObliviousSpartan)
Just Enough Resources (JER) (by way2muchnoise)
CoFH World (by TeamCoFH)
B.A.S.E (by lanse505)
Hammer (Lib) Core (by Zeitheron)
Just Enough Items (JEI) (by mezz)
Thaumic Brewing (by daedalus4096)
Material Changer (by Lellson8)
Thaumic Speedup (by Rongmario)
Chisel (by tterrag1098)
Redstone Flux (by TeamCoFH)
Crimson Revelations (by mobiusflip)
Thaumic Periphery (by cadaverous_queen)
Spartan Weaponry Arcana (by ObliviousSpartan)
Mystical Mechanics API (by BordListian)
Thaumcraft (by Azanor13)
Crimson Warfare (by Ta6e)
Spartan Shields (by ObliviousSpartan)
Thaumic Augmentation (by TheCodex6824)
Neat (by Vazkii)
Consecration (by TheIllusiveC4)
ModTweaker (by Jaredlll08)
