### ISSUE TITLE
[Question] Icon Images

### ISSUE THREAD

**Issue by VerySaltyOreos** [TheCodex6824/ThaumcraftResearchPatcher#12]
From what I can tell using the docs I can only reference images from mods or items, is there a way to refer to images not from a mod's jar? 
I'm not familiar with this sort of stuff, so please bear with me for not understanding.

**Comment by DaRetroCat** [comment]
Basically! Though you can use textures from resource-packs since they basically act as fake mod jars that contain only resources and no code. You could also use a mod like https://www.curseforge.com/minecraft/mc-mods/resource-loader as a cleaner alternative to resource packs

**Comment by VerySaltyOreos** [comment]
> Basically! Though you can use textures from resource-packs aswell since they basically act as fake mod jars that contain only resources and no code. You could also use a mod like https://www.curseforge.com/minecraft/mc-mods/resource-loader as a cleaner alternative to resource packs

I'll look into that mod, cause the only other option I could think of is making individual items for the textures using contenttweaker.
That wouldn't be a problem if I was just needing a few icons for a category, but I'm making an entire mob bestiary tab.
I do not need that many placeholder items clogging up my game.

**Comment by VerySaltyOreos** [comment]
could you give an example since I'm not familiar with the mod?

**Comment by DaRetroCat** [comment]
Oh alright, if ya cant figure something else out feel free to ask
