### ISSUE TITLE
recipes

### ISSUE THREAD

**Issue by Kitsunyy** [TheCodex6824/ThaumcraftResearchPatcher#2]
how to add custom recipes? Crafting is changed using craft tweaker, when you add this crafting - it is not displayed...
![image](https://user-images.githubusercontent.com/56004431/106356638-54e83f80-6312-11eb-9b86-0a914a874b67.png)
![image](https://user-images.githubusercontent.com/56004431/106356651-5fa2d480-6312-11eb-8539-61e180be8123.png)
![image](https://user-images.githubusercontent.com/56004431/106356659-6a5d6980-6312-11eb-8f86-f167d114a5d0.png)

**Comment by Kitsunyy** [comment]
For the modpack, it is necessary that the item is displayed in the book, because when you add stages to any item from thaumcraft, it breaks the craft...
"https://github.com/jaredlll08/RecipeStages/issues/34"

**Comment by TheCodex6824** [comment]
Are there any errors in the logs? I see there's an extra `,` after your entry that will probably cause a JSON parse error, not sure if that's the problem or you just copied that entry to its own file to show and forgot to remove it.

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106367721-a9f97500-6355-11eb-8f5b-f25fc9a246f9.png)
![image](https://user-images.githubusercontent.com/56004431/106367726-b1b91980-6355-11eb-859f-8393475f73b6.png)
![image](https://user-images.githubusercontent.com/56004431/106367737-c4335300-6355-11eb-8578-60c72b8cce30.png)

**Comment by TheCodex6824** [comment]
I'm assuming you're using CraftTweaker or something to make that infusion recipe; if so, try "crafttweaker:witches_oven" (or whatever you called the recipe). Otherwise, what mod are you using to add the recipe (or is that part of Bewitchment TC compat or something)?

**Comment by Kitsunyy** [comment]
Yeah, its crafttweaker, i said this in the first message. But I'm not sure that's how it works...
![image](https://user-images.githubusercontent.com/56004431/106369084-98b56600-635f-11eb-8059-a6fdd9573f98.png)
![image](https://user-images.githubusercontent.com/56004431/106369104-ca2e3180-635f-11eb-973f-107d5d9553bb.png)
And this... :(
![image](https://user-images.githubusercontent.com/56004431/106369128-e92cc380-635f-11eb-94f3-8ff5df5d3a37.png)
![image](https://user-images.githubusercontent.com/56004431/106369131-f053d180-635f-11eb-905e-32eb6af55e39.png)

**Comment by TheCodex6824** [comment]
> Yeah, its crafttweaker, i said this in the first message. But I'm not sure that's how it works...

Sorry, that's what I get for not paying close enough attention. There should be a command like `/ct recipeNames` or something similar, can you check the output of that to see if the witches' oven recipe is there and what it is called?

**Comment by Kitsunyy** [comment]
Hmm, I don't quite know what to do with it...
![image](https://user-images.githubusercontent.com/56004431/106369454-8ee13200-6362-11eb-9c90-8b76abcc597d.png)

**Comment by TheCodex6824** [comment]
Ok so that log is useless for infusion recipes, good to know. I'll have to check the code later to see why this is going on but in the meantime, the last suggestion I have to try is "thaumcraft:witchesOven" or "thaumcraft:witches_oven".

**Comment by Kitsunyy** [comment]
Oh man, i love u, TY <3 
![image](https://user-images.githubusercontent.com/56004431/106369528-61e14f00-6363-11eb-933a-080eb77a9616.png)
![image](https://user-images.githubusercontent.com/56004431/106369530-66a60300-6363-11eb-9a9b-e069c466b3aa.png)
