### ISSUE TITLE
Pathes...

### ISSUE THREAD

**Issue by Kitsunyy** [TheCodex6824/ThaumcraftResearchPatcher#3]
well... Hello again... I want to replace recipes in stages, but I absolutely can't understand how it works.. I do everything on the wiki, but I catch constant errors, such as: 
![image](https://user-images.githubusercontent.com/56004431/106395360-f8207e00-6412-11eb-943a-f66c20b4db33.png)
in the script, everything looks like this, here is the remove operator, because it is easier to work with it. 
![image](https://user-images.githubusercontent.com/56004431/106395387-1c7c5a80-6413-11eb-9e67-5436c3a71dce.png)
I tried different variations, but everything leads to this error in the log..

**Comment by TheCodex6824** [comment]
Arrays are zero-indexed, meaning that the first index is 0 and the last will be (size - 1). I think the First Steps research has 3 recipes, so removing the last one should use index 2. I do have to say though that I really should have a better (more user-friendly) error message for that.

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106463761-e093d480-64a8-11eb-8aa1-1db1aef8b69e.png)
![image](https://user-images.githubusercontent.com/56004431/106463812-edb0c380-64a8-11eb-8464-d2e3f36f2387.png)
Hmmm

**Comment by TheCodex6824** [comment]
Oh that first `3` should also be a `2` for the same reason, sorry for not noticing that! So this should work: `stages/2/recipes/2`

**Comment by Kitsunyy** [comment]
yeah, its worked, but, can I delete everything at once in one line?

**Comment by TheCodex6824** [comment]
You might be able to do something like this:
```
[
    {
        "key": "FIRSTSTEPS",
        "ops": [
            {
                "op": "remove",
                "path": "stages/2/recipes"
            },
            {
                "op": "add",
                "path": "stages/2/recipes",
                "value": []
            }
        ]
    }
]
```

Your recipes would go in the value of the `add` operation (or you can add them later). This is untested so there might be syntax errors but that's the general idea.

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106483679-dc26e600-64bf-11eb-93ea-1efda9589625.png)
![image](https://user-images.githubusercontent.com/56004431/106483733-e77a1180-64bf-11eb-9a4d-86a3c1b842c1.png)
Still the same problem..

**Comment by TheCodex6824** [comment]
instead of `"minecraft:chest"` put:
```
[
    "minecraft:chest"
]
```
(Notice that it's an array, even though it only has a single element)

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106484312-8ef74400-64c0-11eb-908a-9e8a59c95b17.png)
Yeah, but..
![image](https://user-images.githubusercontent.com/56004431/106484482-b5b57a80-64c0-11eb-9a89-90c45bc2729c.png)

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106484805-0331e780-64c1-11eb-9de7-cbd647d911c8.png)
![image](https://user-images.githubusercontent.com/56004431/106484835-0cbb4f80-64c1-11eb-9557-4edb577e2632.png)
Yes, the items are removed, but the chest still doesnt show up :(

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106485035-3d9b8480-64c1-11eb-8a5c-410952274633.png)
and log

**Comment by TheCodex6824** [comment]
That one might be a bug, I have to check the json patch check to see if what I suggested is allowed and if so why its breaking. In the meantime, the following should work:
```
[
    {
        "key": "FIRSTSTEPS",
        "ops": [
            {
                "op": "remove",
                "path": "stages/2/recipes"
            },
            {
                "op": "add",
                "path": "stages/2/recipes",
                "value": []
            },
            {
                "op": "add",
                "path": "stages/2/recipes/-",
                "value": "minecraft:chest"
            }
        ]
    }
]
```

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106487747-0b3f5680-64c4-11eb-8822-28798fb2371e.png)
![image](https://user-images.githubusercontent.com/56004431/106487810-1befcc80-64c4-11eb-9dc1-283d0efee7d7.png)
![image](https://user-images.githubusercontent.com/56004431/106487858-29a55200-64c4-11eb-8716-1240b1aa48fe.png)
And This:
![image](https://user-images.githubusercontent.com/56004431/106487949-3fb31280-64c4-11eb-8278-a1e676dbda13.png)
![image](https://user-images.githubusercontent.com/56004431/106487971-46da2080-64c4-11eb-8e1e-21ff834bd801.png)
![image](https://user-images.githubusercontent.com/56004431/106488011-50fc1f00-64c4-11eb-99c3-32c5a68a6f61.png)

**Comment by TheCodex6824** [comment]
Last suggestion I have is to try removing / fixing that invalid entry the log is complaining about, other than that I have to check later for a possible bug (in class atm)

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106489261-a1c04780-64c5-11eb-8820-0557fde30b0e.png)
![image](https://user-images.githubusercontent.com/56004431/106489278-a684fb80-64c5-11eb-960e-259b559fa566.png)
no :(

**Comment by TheCodex6824** [comment]
So this is a bit odd but this works for me:
```
{
    "key": "FIRSTSTEPS",
    "ops": [
	{
		"op": "remove",
		"path": "stages/2/recipes"
	},
	{
		"op": "add",
		"path": "stages/2/recipes",
		"value": ["minecraft:chest"]
	}
    ]
}
```
Did you edit the chest recipe in CraftTweaker or something? The only thing I can think of is that the chest recipe is not found...

**Comment by Kitsunyy** [comment]
![image](https://user-images.githubusercontent.com/56004431/106592317-6a52a900-6560-11eb-8028-f300b52249f9.png)
yeah, but the chests are in stages, does it matter?...

**Comment by Kitsunyy** [comment]
Its worked:
![image](https://user-images.githubusercontent.com/56004431/106595785-1dbd9c80-6565-11eb-9ad3-41f50f0a2d0e.png)
![image](https://user-images.githubusercontent.com/56004431/106595804-27470480-6565-11eb-9a1b-d7744e388e6e.png)
but, thaumcraft will also be in the stages.. I think it might break crafting again.. Anyway, thank you so much, again..
