### ISSUE TITLE
Thaumic wands compatibility issue

### ISSUE THREAD

**Issue by DaRetroCat** [TheCodex6824/ThaumcraftResearchPatcher#4]
Due to thaumic wands for some reason opting to not use the json research method this makes any of its research entries completely unchangeable from any method ive tried which is quite annoying and means having complete thaumanomicon overhauls with wands arnt completely possible (as you have to have all the thaumic wands entries intact)

**Comment by TheCodex6824** [comment]
So it seems like Thaumic Wands research is hardcoded into the mod. There are also some other issues:
- The first steps recipes are overwritten in postInit, which means they might nuke any changes patches make to that
- When /tc reload is executed, it waits for Thaumcraft to clear the research, then adds its hardcoded research back, meaning that it's up to timing whether the patches work or not

Honestly, it might be best just to ask the author of that addon to consider switching to JSON research (or at least, start a discussion on why that doesn't work for them).

**Comment by DaRetroCat** [comment]
Alright ill go do that, for now guess my only option is to make a completely new category to be the start tab and simply make it impossible to access either the normal fundamentals tab or the thaumic wands tab. Thanks for the help
