### ISSUE TITLE
Documentation missing colon

### ISSUE THREAD

**Issue by WaitingIdly** [TheCodex6824/ThaumcraftResearchPatcher#6]
On your Patching Existing Research Entries page, under the Format section, you missed a single colon after `"op"`. This is the only colon you missed.
Pretty sure this is why that one person had that issue on curseforge.
![image](https://user-images.githubusercontent.com/25394029/108813840-9b723800-7566-11eb-9f2e-eeca7ca399c4.png)

**Comment by TheCodex6824** [comment]
Wow I can't believe I missed that, thanks for pointing that out. It should be fixed now.
