### ISSUE TITLE
Crafttweaker Recipes not Locking behind Custom research.

### ISSUE THREAD

**Issue by MerrittK** [TheCodex6824/ThaumcraftResearchPatcher#7]
With the custom entry:
{
    "entries" :[
        {
        "key": "BLOODALTAR",    
        "name": "research.BLOODALTAR.title",
        "icons": [ "bloodmagic:altar" ],
        "category": "ALCHEMY", "location": [ -3,-2 ], 
        "parents": [ "HEDGEALCHEMY" ],       
        "stages": [
                {
                    "text": "research.BLOODALTAR.stage.1",
					"required_knowledge":["THEORY;ALCHEMY;1"],
                    "warp": 3,
					"recipes": ["bloodmagic:altar"]
                },
				{
                    "text": "research.BLOODALTAR.stage.2",
					"required_knowledge":["THEORY;ALCHEMY;1"],
					"recipes": ["bloodmagic:altar"]
                }
            ]
        },
    ]
}

And the zs script:
mods.thaumcraft.ArcaneWorkbench.registerShapelessRecipe("tests", "BLOODALTAR", 5, 
  [<aspect:aqua>, <aspect:ignis>, <aspect:terra>], <bloodmagic:altar>, 
  [<minecraft:sand>, <minecraft:stick>, <minecraft:grass>]);

The recipe is available before the custom research is finished. This is a major issue, since it makes it impossible to implement custom recipes tied to unique research.

Mod list:  
  [✔️] AutoRegLib-1.3-32
  [✔️] Baubles-1.12-1.5.2
  [✔️] BloodMagic-1.12.2-2.4.3-105
  [✔️] Controlling-3.0.10
  [✔️] CraftTweaker2-1.12-4.1.20.646
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Guide-API-1.12-2.1.8-63
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] modtweaker-4.0.18
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MTLib-3.0.6
  [✔️] Patchouli-1.0-23.6
  [✔️] Quark-r1.6-179
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] tc6aspects4jei-0.0.2a
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumcraftResearchPatcher-1.12.2-1.0.0
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] theoneprobe-1.12-1.4.28

**Comment by TheCodex6824** [comment]
If you can provide a reproducing test script that doesn't require any extra mods I'll investigate this

**Comment by TheCodex6824** [comment]
While looking into this again I just noticed: in your research json you are using "bloodmagic:altar" as your recipe, but your crafttweaker script is adding a recipe named "thaumcraft:tests" (it appends thaumcraft: before the recipe name). The recipe name needs to be the exact name of the recipe, not the item.

**Comment by MerrittK** [comment]
Thanks!
