### ISSUE TITLE
Thaumic Additions

### ISSUE THREAD

**Issue by willtarax** [TheCodex6824/ThaumcraftResearchPatcher#9]
My Thaumic Additions tab has disappeared on me when I updated to 1.1.1

**Comment by DaRetroCat** [comment]
I believe thaumcraft research patcher is mistaking thaumic addition's hardcoded research entries as them not existing at all and automatically removing the tab a easy fix imo would to simply make category removing manual

**Comment by TheCodex6824** [comment]
Additions registers it's research in postInit (which is arguably wrong behavior but whatever), so the patcher sees the category as having no entries and deletes it.

**Comment by VerySaltyOreos** [comment]
> Additions registers it's research in postInit (which is arguably wrong behavior but whatever), so the patcher sees the category as having no entries and deletes it.

Is that why additions will sometimes cause a crash when doing /tc reload ?
